// Code generated by protoc-gen-go. DO NOT EDIT.
// source: services/virtualmachine.proto

package virtualmachine // import "github.com/orbs-network/go-scaffold/types/services/virtualmachine"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import protocol "github.com/orbs-network/go-scaffold/types/protocol"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ProcessTransactionInput struct {
	Method               string                `protobuf:"bytes,1,opt,name=method" json:"method,omitempty"`
	Arg                  *protocol.Transaction `protobuf:"bytes,2,opt,name=arg" json:"arg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ProcessTransactionInput) Reset()         { *m = ProcessTransactionInput{} }
func (m *ProcessTransactionInput) String() string { return proto.CompactTextString(m) }
func (*ProcessTransactionInput) ProtoMessage()    {}
func (*ProcessTransactionInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_virtualmachine_dfcbd512b24fd566, []int{0}
}
func (m *ProcessTransactionInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessTransactionInput.Unmarshal(m, b)
}
func (m *ProcessTransactionInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessTransactionInput.Marshal(b, m, deterministic)
}
func (dst *ProcessTransactionInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessTransactionInput.Merge(dst, src)
}
func (m *ProcessTransactionInput) XXX_Size() int {
	return xxx_messageInfo_ProcessTransactionInput.Size(m)
}
func (m *ProcessTransactionInput) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessTransactionInput.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessTransactionInput proto.InternalMessageInfo

func (m *ProcessTransactionInput) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *ProcessTransactionInput) GetArg() *protocol.Transaction {
	if m != nil {
		return m.Arg
	}
	return nil
}

type ProcessTransactionOutput struct {
	Result               int32    `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProcessTransactionOutput) Reset()         { *m = ProcessTransactionOutput{} }
func (m *ProcessTransactionOutput) String() string { return proto.CompactTextString(m) }
func (*ProcessTransactionOutput) ProtoMessage()    {}
func (*ProcessTransactionOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_virtualmachine_dfcbd512b24fd566, []int{1}
}
func (m *ProcessTransactionOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessTransactionOutput.Unmarshal(m, b)
}
func (m *ProcessTransactionOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessTransactionOutput.Marshal(b, m, deterministic)
}
func (dst *ProcessTransactionOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessTransactionOutput.Merge(dst, src)
}
func (m *ProcessTransactionOutput) XXX_Size() int {
	return xxx_messageInfo_ProcessTransactionOutput.Size(m)
}
func (m *ProcessTransactionOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessTransactionOutput.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessTransactionOutput proto.InternalMessageInfo

func (m *ProcessTransactionOutput) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

type CallContractInput struct {
	Method               string            `protobuf:"bytes,1,opt,name=method" json:"method,omitempty"`
	Arg                  *protocol.Address `protobuf:"bytes,2,opt,name=arg" json:"arg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CallContractInput) Reset()         { *m = CallContractInput{} }
func (m *CallContractInput) String() string { return proto.CompactTextString(m) }
func (*CallContractInput) ProtoMessage()    {}
func (*CallContractInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_virtualmachine_dfcbd512b24fd566, []int{2}
}
func (m *CallContractInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallContractInput.Unmarshal(m, b)
}
func (m *CallContractInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallContractInput.Marshal(b, m, deterministic)
}
func (dst *CallContractInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallContractInput.Merge(dst, src)
}
func (m *CallContractInput) XXX_Size() int {
	return xxx_messageInfo_CallContractInput.Size(m)
}
func (m *CallContractInput) XXX_DiscardUnknown() {
	xxx_messageInfo_CallContractInput.DiscardUnknown(m)
}

var xxx_messageInfo_CallContractInput proto.InternalMessageInfo

func (m *CallContractInput) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *CallContractInput) GetArg() *protocol.Address {
	if m != nil {
		return m.Arg
	}
	return nil
}

type CallContractOutput struct {
	Result               int32    `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CallContractOutput) Reset()         { *m = CallContractOutput{} }
func (m *CallContractOutput) String() string { return proto.CompactTextString(m) }
func (*CallContractOutput) ProtoMessage()    {}
func (*CallContractOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_virtualmachine_dfcbd512b24fd566, []int{3}
}
func (m *CallContractOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallContractOutput.Unmarshal(m, b)
}
func (m *CallContractOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallContractOutput.Marshal(b, m, deterministic)
}
func (dst *CallContractOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallContractOutput.Merge(dst, src)
}
func (m *CallContractOutput) XXX_Size() int {
	return xxx_messageInfo_CallContractOutput.Size(m)
}
func (m *CallContractOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_CallContractOutput.DiscardUnknown(m)
}

var xxx_messageInfo_CallContractOutput proto.InternalMessageInfo

func (m *CallContractOutput) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func init() {
	proto.RegisterType((*ProcessTransactionInput)(nil), "virtualmachine.ProcessTransactionInput")
	proto.RegisterType((*ProcessTransactionOutput)(nil), "virtualmachine.ProcessTransactionOutput")
	proto.RegisterType((*CallContractInput)(nil), "virtualmachine.CallContractInput")
	proto.RegisterType((*CallContractOutput)(nil), "virtualmachine.CallContractOutput")
}

func init() {
	proto.RegisterFile("services/virtualmachine.proto", fileDescriptor_virtualmachine_dfcbd512b24fd566)
}

var fileDescriptor_virtualmachine_dfcbd512b24fd566 = []byte{
	// 303 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x41, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0xa9, 0xe2, 0xc0, 0x28, 0x83, 0x05, 0xd4, 0x31, 0x11, 0x66, 0x3d, 0x6c, 0x07, 0xd7,
	0xc0, 0xfc, 0x04, 0x3a, 0x3c, 0x78, 0x10, 0xc7, 0x50, 0x0f, 0xbb, 0x65, 0xe9, 0xa3, 0x0d, 0xb6,
	0x49, 0x79, 0x79, 0x9d, 0xfa, 0x2d, 0xfd, 0x48, 0x62, 0x5b, 0x59, 0x5d, 0x59, 0x3d, 0xbe, 0xd7,
	0x7f, 0x7f, 0xf9, 0xe7, 0x47, 0xd8, 0x85, 0x03, 0x5c, 0x6b, 0x05, 0x4e, 0xac, 0x35, 0x52, 0x2e,
	0x93, 0x54, 0xaa, 0x58, 0x1b, 0x08, 0x32, 0xb4, 0x64, 0x79, 0xf7, 0xef, 0x76, 0x70, 0x5e, 0xac,
	0x95, 0x4d, 0x04, 0xa1, 0x34, 0x4e, 0x2a, 0xd2, 0xd6, 0xb8, 0x32, 0xec, 0x2f, 0xd9, 0xd9, 0x1c,
	0xad, 0x02, 0xe7, 0x9e, 0x37, 0x1f, 0x1f, 0x4c, 0x96, 0x13, 0x3f, 0x65, 0x9d, 0x14, 0x28, 0xb6,
	0x61, 0xdf, 0x1b, 0x7a, 0xe3, 0xc3, 0x45, 0x35, 0xf1, 0x11, 0xdb, 0x97, 0x18, 0xf5, 0xf7, 0x86,
	0xde, 0xf8, 0x68, 0x7a, 0x12, 0xfc, 0xd2, 0x83, 0x1a, 0x60, 0xf1, 0x93, 0xf0, 0xa7, 0xac, 0xdf,
	0x64, 0x3f, 0xe5, 0x54, 0xc1, 0x11, 0x5c, 0x9e, 0x50, 0x01, 0x3f, 0x58, 0x54, 0x93, 0x3f, 0x67,
	0xbd, 0x99, 0x4c, 0x92, 0x99, 0x35, 0x84, 0x52, 0x51, 0x7b, 0x93, 0xab, 0x7a, 0x93, 0xde, 0xa6,
	0xc9, 0x6d, 0x18, 0x22, 0x38, 0x57, 0xb6, 0xb8, 0x66, 0xbc, 0x4e, 0x6c, 0x3f, 0x7f, 0xfa, 0xe5,
	0xb1, 0xee, 0x6b, 0xe9, 0xef, 0xb1, 0xf4, 0xc7, 0x23, 0xc6, 0x9b, 0xd7, 0xe0, 0xa3, 0x60, 0x4b,
	0xfe, 0x0e, 0x8d, 0x83, 0xf1, 0xff, 0xc1, 0xaa, 0xd3, 0x0b, 0x3b, 0xae, 0x37, 0xe5, 0x97, 0xdb,
	0x7f, 0x36, 0xcc, 0x0c, 0xfc, 0xb6, 0x48, 0x89, 0xbd, 0xbb, 0x5f, 0xce, 0x22, 0x4d, 0x71, 0xbe,
	0x0a, 0x94, 0x4d, 0x85, 0xc5, 0x95, 0x9b, 0x18, 0xa0, 0x77, 0x8b, 0x6f, 0x22, 0xb2, 0x13, 0xf8,
	0xc8, 0x00, 0x75, 0x0a, 0x86, 0x04, 0x7d, 0x66, 0xe0, 0xc4, 0x8e, 0xc7, 0xb5, 0xea, 0x14, 0x7a,
	0x6f, 0xbe, 0x03, 0x00, 0x00, 0xff, 0xff, 0xa4, 0x15, 0x32, 0x64, 0x7e, 0x02, 0x00, 0x00,
}
