// Code generated by protoc-gen-go. DO NOT EDIT.
// source: services/publicapi.proto

package publicapi // import "github.com/orbs-network/go-scaffold/types/services/publicapi"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import protocol "github.com/orbs-network/go-scaffold/types/protocol"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TransferInput struct {
	Transaction          *protocol.Transaction `protobuf:"bytes,1,opt,name=transaction" json:"transaction,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *TransferInput) Reset()         { *m = TransferInput{} }
func (m *TransferInput) String() string { return proto.CompactTextString(m) }
func (*TransferInput) ProtoMessage()    {}
func (*TransferInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_publicapi_3123bbc188048872, []int{0}
}
func (m *TransferInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransferInput.Unmarshal(m, b)
}
func (m *TransferInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransferInput.Marshal(b, m, deterministic)
}
func (dst *TransferInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransferInput.Merge(dst, src)
}
func (m *TransferInput) XXX_Size() int {
	return xxx_messageInfo_TransferInput.Size(m)
}
func (m *TransferInput) XXX_DiscardUnknown() {
	xxx_messageInfo_TransferInput.DiscardUnknown(m)
}

var xxx_messageInfo_TransferInput proto.InternalMessageInfo

func (m *TransferInput) GetTransaction() *protocol.Transaction {
	if m != nil {
		return m.Transaction
	}
	return nil
}

type TransferOutput struct {
	Success              string   `protobuf:"bytes,1,opt,name=success" json:"success,omitempty"`
	Result               int32    `protobuf:"varint,2,opt,name=result" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransferOutput) Reset()         { *m = TransferOutput{} }
func (m *TransferOutput) String() string { return proto.CompactTextString(m) }
func (*TransferOutput) ProtoMessage()    {}
func (*TransferOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_publicapi_3123bbc188048872, []int{1}
}
func (m *TransferOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransferOutput.Unmarshal(m, b)
}
func (m *TransferOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransferOutput.Marshal(b, m, deterministic)
}
func (dst *TransferOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransferOutput.Merge(dst, src)
}
func (m *TransferOutput) XXX_Size() int {
	return xxx_messageInfo_TransferOutput.Size(m)
}
func (m *TransferOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_TransferOutput.DiscardUnknown(m)
}

var xxx_messageInfo_TransferOutput proto.InternalMessageInfo

func (m *TransferOutput) GetSuccess() string {
	if m != nil {
		return m.Success
	}
	return ""
}

func (m *TransferOutput) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

type GetBalanceInput struct {
	From                 *protocol.Address `protobuf:"bytes,1,opt,name=from" json:"from,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetBalanceInput) Reset()         { *m = GetBalanceInput{} }
func (m *GetBalanceInput) String() string { return proto.CompactTextString(m) }
func (*GetBalanceInput) ProtoMessage()    {}
func (*GetBalanceInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_publicapi_3123bbc188048872, []int{2}
}
func (m *GetBalanceInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBalanceInput.Unmarshal(m, b)
}
func (m *GetBalanceInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBalanceInput.Marshal(b, m, deterministic)
}
func (dst *GetBalanceInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBalanceInput.Merge(dst, src)
}
func (m *GetBalanceInput) XXX_Size() int {
	return xxx_messageInfo_GetBalanceInput.Size(m)
}
func (m *GetBalanceInput) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBalanceInput.DiscardUnknown(m)
}

var xxx_messageInfo_GetBalanceInput proto.InternalMessageInfo

func (m *GetBalanceInput) GetFrom() *protocol.Address {
	if m != nil {
		return m.From
	}
	return nil
}

type GetBalanceOutput struct {
	Success              string   `protobuf:"bytes,1,opt,name=success" json:"success,omitempty"`
	Result               int32    `protobuf:"varint,2,opt,name=result" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBalanceOutput) Reset()         { *m = GetBalanceOutput{} }
func (m *GetBalanceOutput) String() string { return proto.CompactTextString(m) }
func (*GetBalanceOutput) ProtoMessage()    {}
func (*GetBalanceOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_publicapi_3123bbc188048872, []int{3}
}
func (m *GetBalanceOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBalanceOutput.Unmarshal(m, b)
}
func (m *GetBalanceOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBalanceOutput.Marshal(b, m, deterministic)
}
func (dst *GetBalanceOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBalanceOutput.Merge(dst, src)
}
func (m *GetBalanceOutput) XXX_Size() int {
	return xxx_messageInfo_GetBalanceOutput.Size(m)
}
func (m *GetBalanceOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBalanceOutput.DiscardUnknown(m)
}

var xxx_messageInfo_GetBalanceOutput proto.InternalMessageInfo

func (m *GetBalanceOutput) GetSuccess() string {
	if m != nil {
		return m.Success
	}
	return ""
}

func (m *GetBalanceOutput) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func init() {
	proto.RegisterType((*TransferInput)(nil), "publicapi.TransferInput")
	proto.RegisterType((*TransferOutput)(nil), "publicapi.TransferOutput")
	proto.RegisterType((*GetBalanceInput)(nil), "publicapi.GetBalanceInput")
	proto.RegisterType((*GetBalanceOutput)(nil), "publicapi.GetBalanceOutput")
}

func init() { proto.RegisterFile("services/publicapi.proto", fileDescriptor_publicapi_3123bbc188048872) }

var fileDescriptor_publicapi_3123bbc188048872 = []byte{
	// 305 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0xcd, 0x4e, 0xf3, 0x30,
	0x10, 0x54, 0x3e, 0x7d, 0x14, 0xba, 0x15, 0x7f, 0x96, 0x40, 0x21, 0xbd, 0x54, 0x91, 0x90, 0x7a,
	0x69, 0x2c, 0x95, 0x03, 0x9c, 0x80, 0x56, 0x20, 0xe0, 0x04, 0x8a, 0x7a, 0xe2, 0x96, 0xb8, 0xdb,
	0x62, 0x91, 0xda, 0x96, 0xd7, 0xe6, 0xe7, 0x39, 0x78, 0x61, 0xd4, 0xb4, 0x21, 0x05, 0x7a, 0xe2,
	0xb8, 0x33, 0xe3, 0xf1, 0xec, 0x68, 0x21, 0x24, 0xb4, 0x2f, 0x52, 0x20, 0x71, 0xe3, 0xf3, 0x42,
	0x8a, 0xcc, 0xc8, 0xc4, 0x58, 0xed, 0x34, 0x6b, 0x7e, 0x01, 0x51, 0xbb, 0x44, 0x84, 0x2e, 0xb8,
	0xb3, 0x99, 0xa2, 0x4c, 0x38, 0xa9, 0x15, 0x2d, 0x74, 0xf1, 0x2d, 0x6c, 0x8f, 0xe6, 0xe8, 0x04,
	0xed, 0x9d, 0x32, 0xde, 0xb1, 0x53, 0x68, 0xad, 0xc8, 0xc2, 0xa0, 0x13, 0x74, 0x5b, 0xfd, 0x83,
	0xa4, 0xf2, 0x48, 0x46, 0x35, 0x99, 0xae, 0x2a, 0xe3, 0x21, 0xec, 0x54, 0x4e, 0xf7, 0xde, 0xcd,
	0xad, 0x42, 0xd8, 0x24, 0x2f, 0x04, 0x12, 0x95, 0x36, 0xcd, 0xb4, 0x1a, 0xd9, 0x21, 0x34, 0x2c,
	0x92, 0x2f, 0x5c, 0xf8, 0xaf, 0x13, 0x74, 0x37, 0xd2, 0xe5, 0x14, 0x9f, 0xc1, 0xee, 0x0d, 0xba,
	0x61, 0x56, 0x64, 0x4a, 0xe0, 0x22, 0xcf, 0x31, 0xfc, 0x9f, 0x58, 0x3d, 0x5b, 0x06, 0xd9, 0xaf,
	0x83, 0x0c, 0xc6, 0x63, 0x8b, 0x44, 0x69, 0x49, 0xc7, 0x57, 0xb0, 0x57, 0xbf, 0xfc, 0xeb, 0xff,
	0xfd, 0x8f, 0x00, 0x9a, 0x0f, 0x65, 0x71, 0x03, 0x23, 0xd9, 0x05, 0x6c, 0x55, 0x1b, 0xb1, 0x30,
	0xa9, 0x1b, 0xfe, 0x56, 0x58, 0x74, 0xb4, 0x86, 0x59, 0x06, 0xb8, 0x06, 0xa8, 0x43, 0xb1, 0x68,
	0x45, 0xf8, 0x63, 0xcb, 0xa8, 0xbd, 0x96, 0x5b, 0xd8, 0x0c, 0x2f, 0x1f, 0xcf, 0xa7, 0xd2, 0x3d,
	0xf9, 0x3c, 0x11, 0x7a, 0xc6, 0xb5, 0xcd, 0xa9, 0xa7, 0xd0, 0xbd, 0x6a, 0xfb, 0xcc, 0xa7, 0xba,
	0x87, 0x6f, 0x06, 0xad, 0x9c, 0xa1, 0x72, 0xdc, 0xbd, 0x1b, 0x24, 0xfe, 0xfb, 0x26, 0xf2, 0x46,
	0xd9, 0xda, 0xc9, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff, 0x77, 0x40, 0x7a, 0x2f, 0x30, 0x02, 0x00,
	0x00,
}
