// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocol/transactions.proto

package protocol // import "github.com/orbs-network/go-experiment/types/protocol"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Address struct {
	Username             string   `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Address) Reset()         { *m = Address{} }
func (m *Address) String() string { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()    {}
func (*Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_transactions_997014fe07e576be, []int{0}
}
func (m *Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Address.Unmarshal(m, b)
}
func (m *Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Address.Marshal(b, m, deterministic)
}
func (dst *Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Address.Merge(dst, src)
}
func (m *Address) XXX_Size() int {
	return xxx_messageInfo_Address.Size(m)
}
func (m *Address) XXX_DiscardUnknown() {
	xxx_messageInfo_Address.DiscardUnknown(m)
}

var xxx_messageInfo_Address proto.InternalMessageInfo

func (m *Address) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type Transaction struct {
	From                 *Address `protobuf:"bytes,1,opt,name=from" json:"from,omitempty"`
	To                   *Address `protobuf:"bytes,2,opt,name=to" json:"to,omitempty"`
	Amount               int32    `protobuf:"varint,3,opt,name=amount" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_transactions_997014fe07e576be, []int{1}
}
func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (dst *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(dst, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetFrom() *Address {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *Transaction) GetTo() *Address {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *Transaction) GetAmount() int32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func init() {
	proto.RegisterType((*Address)(nil), "protocol.Address")
	proto.RegisterType((*Transaction)(nil), "protocol.Transaction")
}

func init() {
	proto.RegisterFile("protocol/transactions.proto", fileDescriptor_transactions_997014fe07e576be)
}

var fileDescriptor_transactions_997014fe07e576be = []byte{
	// 198 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0xcc, 0x31, 0x4f, 0x84, 0x40,
	0x10, 0x05, 0xe0, 0x80, 0x8a, 0xb8, 0x54, 0x6e, 0x61, 0x88, 0x36, 0x48, 0x42, 0x42, 0xc3, 0x6e,
	0xa2, 0xc6, 0x5e, 0x7f, 0x02, 0xb1, 0xb2, 0x5b, 0x60, 0x44, 0xa2, 0xbb, 0x43, 0x66, 0x87, 0xdc,
	0xdd, 0xbf, 0xbf, 0x64, 0x03, 0x77, 0xd5, 0x75, 0xf3, 0xe6, 0xbd, 0x7c, 0xe2, 0x69, 0x26, 0x64,
	0xec, 0xf1, 0x5f, 0x33, 0x19, 0xe7, 0x4d, 0xcf, 0x13, 0x3a, 0xaf, 0xc2, 0x57, 0xa6, 0x5b, 0x59,
	0x56, 0xe2, 0xf6, 0x63, 0x18, 0x08, 0xbc, 0x97, 0x8f, 0x22, 0x5d, 0x3c, 0x90, 0x33, 0x16, 0xf2,
	0xa8, 0x88, 0xea, 0xbb, 0xf6, 0x94, 0x4b, 0x14, 0xd9, 0xd7, 0x99, 0x91, 0x95, 0xb8, 0xfe, 0x21,
	0xb4, 0x61, 0x96, 0xbd, 0xdc, 0xab, 0x8d, 0x53, 0xab, 0xd5, 0x86, 0x5a, 0x3e, 0x8b, 0x98, 0x31,
	0x8f, 0x2f, 0x8d, 0x62, 0x46, 0xf9, 0x20, 0x12, 0x63, 0x71, 0x71, 0x9c, 0x5f, 0x15, 0x51, 0x7d,
	0xd3, 0xae, 0xe9, 0xf3, 0xfd, 0xfb, 0x6d, 0x9c, 0xf8, 0x77, 0xe9, 0x54, 0x8f, 0x56, 0x23, 0x75,
	0xbe, 0x71, 0xc0, 0x3b, 0xa4, 0x3f, 0x3d, 0x62, 0x03, 0xfb, 0x19, 0x68, 0xb2, 0xe0, 0x58, 0xf3,
	0x61, 0x06, 0xaf, 0x37, 0xbb, 0x4b, 0xc2, 0xf5, 0x7a, 0x0c, 0x00, 0x00, 0xff, 0xff, 0x77, 0xbc,
	0x86, 0x5b, 0xff, 0x00, 0x00, 0x00,
}
